config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en/ do
    root "static_pages#home"
    
    get "/help", to: "static_pages#help"
    get "/info", to: "static_pages#info"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :courses do
      resources :reviews
      resources :registers
    end
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(index show destroy)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
	  <small>
	    <%= t ".description_1" %>
	  </small>

	  <nav>
	    <ul>
	      <%= t ".info_foot" %>
	      <%= link_to t("further_info_message"), info_path %>
	    </ul>
	  </nav>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home_head"), root_path, class: "glyphicon glyphicon-home" %></li>
        <li><%= link_to t(".help_head"), help_path, class: "glyphicon glyphicon-question-sign" %></li>
        <% if logged_in? %>
           <li><%= link_to t(".users_head"), users_path, class: "glyphicon glyphicon-user" %></li>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", data: {"toggle" =>  "dropdown"}} do %>
              <%= t ".account" %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile_head"), current_user, class: "glyphicon glyphicon-education" %></li>
              <li><%= link_to t(".setting_head"), edit_user_path(current_user), class: "glyphicon glyphicon-edit" %></li>
              <li><%= link_to "Courses", courses_path, class: "glyphicon glyphicon-book" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".logout_head"), logout_path, class: "glyphicon glyphicon-log-out", method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".login_head"), login_path, class: "glyphicon glyphicon-user" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
    <%= yield :title %> | <%= t ".title" %>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>